#########################################
#          Collectibles Config          #
#########################################

# NOTICE: NOT ALL THE CODE IN THIS PLUGIN IS MINE
# Some classes have been provided by Tiffaa, thank you

# Server name
server: "Mythic"